### ISSUE TITLE
Volume of a 3d polyhedron

### ISSUE THREAD

**Issue by lgribeiro** [JoseAntFer/pyny3d#2]
How do I calculate the volume of a 3d polyhedron?

**Comment by JoseAntFer** [comment]
Hi!

That feature is not supported in pyny3d. But in general there are two different cases:

- If the polyhedron is convex you can mesh the interior with tetrahedra and sum the volume of those. For the generation of the tetrahedral mesh you can use Delaunay triangulation (available in scipy.spatial)
- If the polyhedron is non-convex, the problem is much harder and I suggest you look for an online library for this.

Best,
José.

**Comment by lgribeiro** [comment]
@JoseAntFer  thanks for reporting.

I've got solution for both cases:

**1. Convex polyhedron** 
Calculando com PyntCloud
from pyntcloud import PyntCloud
diamond = PyntCloud.from_file("pointcloud.ply")
convex_hull_id = diamond.add_structure("convex_hull")
convex_hull = diamond.structures[convex_hull_id]
volume = convex_hull.volume
print('Volume pyntcloud:',volume)

**2. non-convex polyhedron**
This case is more complex, but in stackoverflow there is a good code/solution
https://stackoverflow.com/questions/1406029/how-to-calculate-the-volume-of-a-3d-mesh-object-the-surface-of-which-is-made-up-t

Thank you, 
Luiz.
